import "./node_modules/bootstrap/dist/css/bootstrap.min.css";
import "./style.scss";

import { addHeading, addContent } from "./addContent.js";
import json from "./assets/data.json";

document.querySelector("#text").innerHTML = `
<h2>QA Process for developing and deploying this site</h2>
<h3>Version Control</h3>
<p>This site is version controlled using git and the repo is publicly hosted at <a href='https://github.com/navaneeth-ashok/SecurityQA'>GitHub</a></p>
<p>The main reason for going with a version control scm like git is because of the reliability it offers, and the availabily of the same.</p>
<h3>Branching model</h3>
<p>The new commits for this repo, are always pushed to a dev branch first. This helps in ensuring that the branch from which Netlify builds the final site is stable, and doesn't have any feature breaking issues</p>
<p>I've created a dummy netlify prpject as well, which builds and deploys this dev branch. This is to ensure that I get to QA test on a producting emulated environment before my code, is pushed to Production.</p>
<h3>Code Linting</h3>
<p>I'm using eslint to ensure that the project doesn't have linting errors, and to achieve this, I've added eslint with airbnb style</p>
<h3>Unit Testing</h3>
<p>To unit test the webpage, I test individual components of the page. 
<h4>List of modules where I unit test</h4>
<ul>
    <li>Navigation Bar : check for links to page are not broken</li>
    <li>Each page : check the data created in data.json under asset folder is showing correctly</li>
    <li>Test the vite build files to ensure all the required files, are built and served</li>
</ul>
<h3>End to End Testing</h3>
<p>For end to end testing, I make sure the build process doesn't show any errors during building<p>
<p>Once the porject is build, I'll check for integration testing by ensuring that all the different divs and p generated by JS is shown</p>
<p>This time, I ensure all the page links are working fine, and I've created few test-cases and plans to emulate end-user scenarios and will test them as well</p>
<h3>Ad-Hoc Testing</h3>
<h4>Ad-hoc testing for this site includes</h4>
<ul>
    <li>HTML Validator</li>
    <li>CSS Validator</li>
    <li>Linting done by eslint</li>
    <li>Lighthouse Auditing</li>
</ul>
<h3>Build Tools</h3>
<p>This site is built using Vite, and I've include SCSS and ES6 JS to make use of the modern build tools and functionalities</p>
<h3>Deployement Pipeling</h3>
<p>The deployment pipeline configured for this page is as follows<p>
<ol>
    <li>Code pushed to Github</li>
    <li>Netlify integrated to GH account to observe for incoming commits, and once commits are pushed, Netlify builds and publishes the site</li>
</ol>

`;
